### ISSUE TITLE
Not available via NuGet

### ISSUE THREAD

**Issue by kjellski** [VerbalExpressions/CSharpVerbalExpressions#27]
Hey there,

with my last Pull Request, you should've merged everything necessary in to deploy this as a NuGet Package to be available via NuGet. I'm just interested in how to publish something to NuGet gallery for public. If you're going to do so, please let me know how it went.

Issue: CSharpVerbalExpressions is not available via NuGet.

Greetings,
Kjellski

P.S.: I've prefilled the `VerbalExpressions\VerbalExpressions.nuspec` with values, feel free to change it accordingly.

**Comment by psoholt** [comment]
https://www.nuget.org/packages/VerbalExpressions-official/
